image: Visual Studio 2017 

before_build: 
    - nuget restore "8.2-downloader/Downloader.sln"

build: 
    project: "8.2-downloader/Downloader.sln"

test_script: 
    - dotnet test "8.2-downloader/Downloader.sln"
