image: Visual Studio 2017 

before_build: 
    - nuget restore "2.3-mergesort/MergeSort.sln"

build: 
    project: "2.3-mergesort/MergeSort.sln"

test_script: 
    - dotnet test "2.3-mergesort/MergeSort.sln"